# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.labelLogo = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo.setMinimumSize(QtCore.QSize(80, 80))
        self.labelLogo.setMaximumSize(QtCore.QSize(100, 100))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setText("")
        self.labelLogo.setObjectName("labelLogo")
        self.headerLayout.addWidget(self.labelLogo)
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setAlignment(QtCore.Qt.AlignVCenter|QtCore.Qt.AlignLeft)
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.headerLayout)
        self.controlsLayout = QtWidgets.QHBoxLayout()
        self.controlsLayout.setObjectName("controlsLayout")
        self.labelTable = QtWidgets.QLabel(self.centralwidget)
        self.labelTable.setObjectName("labelTable")
        self.controlsLayout.addWidget(self.labelTable)
        self.cbTables = QtWidgets.QComboBox(self.centralwidget)
        self.cbTables.setObjectName("cbTables")
        self.controlsLayout.addWidget(self.cbTables)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.controlsLayout.addItem(spacerItem1)
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setObjectName("btnAdd")
        self.controlsLayout.addWidget(self.btnAdd)
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setObjectName("btnEdit")
        self.controlsLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setObjectName("btnDelete")
        self.controlsLayout.addWidget(self.btnDelete)
        self.mainLayout.addLayout(self.controlsLayout)
        self.tableData = QtWidgets.QTableWidget(self.centralwidget)
        self.tableData.setColumnCount(2)
        self.tableData.setRowCount(0)
        self.tableData.setShowGrid(False)
        self.tableData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableData.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableData.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableData.setObjectName("tableData")
        self.tableData.horizontalHeader().setVisible(False)
        self.tableData.verticalHeader().setVisible(False)
        self.mainLayout.addWidget(self.tableData)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Работа с БД"))
        self.labelTitle.setText(_translate("MainWindow", "Просмотр таблиц базы данных"))
        self.labelTable.setText(_translate("MainWindow", "Таблица:"))
        self.btnAdd.setText(_translate("MainWindow", "Добавить запись"))
        self.btnEdit.setText(_translate("MainWindow", "Изменить"))
        self.btnDelete.setText(_translate("MainWindow", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
