# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordDialog(object):
    def setupUi(self, RecordDialog):
        RecordDialog.setObjectName("RecordDialog")
        RecordDialog.resize(500, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(RecordDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(RecordDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollWidget = QtWidgets.QWidget()
        self.scrollWidget.setObjectName("scrollWidget")
        self.formLayout = QtWidgets.QFormLayout(self.scrollWidget)
        self.formLayout.setObjectName("formLayout")
        self.scrollArea.setWidget(self.scrollWidget)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(RecordDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(RecordDialog)
        QtCore.QMetaObject.connectSlotsByName(RecordDialog)

    def retranslateUi(self, RecordDialog):
        _translate = QtCore.QCoreApplication.translate
        RecordDialog.setWindowTitle(_translate("RecordDialog", "Запись"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecordDialog = QtWidgets.QDialog()
    ui = Ui_RecordDialog()
    ui.setupUi(RecordDialog)
    RecordDialog.show()
    sys.exit(app.exec_())
